### PR TITLE
Initial async message communication implementation

### LINKED ISSUE #61: Rewrite serial to make it full async like
Currently it is unstable and blocking on desktop, Android barely works.
Maybe went to thread like communication like on python CLI

### PR DESCRIPTION
**Pull request by Foxushka**
Closes #61 and #122

Test plan:
- [x] - Linux
- [x] - Linux DFU
- [x] - Windows
- [x] - Windows DFU
- [x] - macOS
- [x] - macOS DFU
- [x] - Android OTG
- [x] - Android OTG DFU
- [x] - Android BLE
- [x] - iOS BLE

### CODE REVIEW

**Comment by GameTec-live** [comment]
image

it by default enables everything and trying to select a write mode throws errors. (selecting anything in that menu throws errors???)

Device cant recognize command (translated)
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SerialPortError: Das Gerät erkennt den Befehl nicht., errno = 22
#0      Util.call (package:libserialport/src/util.dart:40:7)
#1      Util.write.<anonymous closure> (package:libserialport/src/util.dart:58:14)
#2      using (package:ffi/src/arena.dart:124:31)
#3      Util.write (package:libserialport/src/util.dart:54:16)
#4      _SerialPortImpl.write (package:libserialport/src/port.dart:361:17)
#5      NativeSerial.write (package:chameleonultragui/connector/serial_native.dart:138:18)
#6      ChameleonCommunicator.sendCmdSync (package:chameleonultragui/bridge/chameleon.dart:344:28)
#7      ChameleonCommunicator.activateSlot (package:chameleonultragui/bridge/chameleon.dart:545:11)
#8      SlotSettingsState.build.<anonymous closure>.<anonymous closure> (package:chameleonultragui/gui/components/slotsettings.dart:285:50)
#9      ToggleButtons.build.<anonymous closure>.<anonymous closure> (package:flutter/src/material/toggle_buttons.dart:795:31)
#10     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)

flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   ChameleonCommunicator.sendCmdSync (package:chameleonultragui/bridge/chameleon.dart:337:9)
flutter: │ #1   ChameleonCommunicator.activateSlot (package:chameleonultragui/bridge/chameleon.dart:545:11)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Sending: 11ef03eb000000011101ff
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SerialPortError: Das Gerät erkennt den Befehl nicht., errno = 22
#0      Util.call (package:libserialport/src/util.dart:40:7)
#1      Util.write.<anonymous closure> (package:libserialport/src/util.dart:58:14)
#2      using (package:ffi/src/arena.dart:124:31)
#3      Util.write (package:libserialport/src/util.dart:54:16)
#4      _SerialPortImpl.write (package:libserialport/src/port.dart:361:17)
#5      NativeSerial.write (package:chameleonultragui/connector/serial_native.dart:138:18)
#6      ChameleonCommunicator.sendCmdSync (package:chameleonultragui/bridge/chameleon.dart:344:28)
#7      ChameleonCommunicator.activateSlot (package:chameleonultragui/bridge/chameleon.dart:545:11)
#8      SlotSettingsState.build.<anonymous closure>.<anonymous closure> (package:chameleonultragui/gui/components/slotsettings.dart:285:50)
#9      ToggleButtons.build.<anonymous closure>.<anonymous closure> (package:flutter/src/material/toggle_buttons.dart:795:31)
#10     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
```

**Comment by GameTec-live** [comment]
okay, nevermind, reconnecting fixed that error

**Review by GameTec-live — APPROVED** [review]
if you tested on linux, merge, windows and android work proerly!

**Comment by pimlie** [comment]
Just wondering, why not use a [MethodChannel](https://docs.flutter.dev/platform-integration/platform-channels) for the serial connection? I thought that was the recommended method to support async communication to platform specific code.

**Comment by Foxushka** [comment]
@pimlie 
1. It's my first flutter project
2. It is working fine
3. We won't rewrite it
4. Your link has nothing with current Dart implementation, it is about Java/Swift and etc. We don't touch this part
5. I don't care

**Pull request merged**
