### PR TITLE
Try to resend command if timeout

### LINKED ISSUE #291: Timeout errors
**Describe the bug**
Once all devices were updated to the most current TestFlight, software and firmware (DEV4). I will get constant timeout errors, 1003 and 4005.

Also, one retrieving keys in any slot, this will happen instantly.   

**To Reproduce**
Steps to reproduce the behavior: Recovering keys in any slot=4005

**Expected behavior**

Since update and DFU update, I will constantly get timeout errors.  

**Screenshots**
image

**Version info:**
 - OS: 17.1, iPhone 12 Pro Max 

 - App build number: 1.0.331

**Also required**:

- [ ✅] - I've upgraded app to latest app version

- [ ✅] - I've upgraded Chameleon firmware to latest version

- [ ✅] - I've searched and verified that there is no already created issues 

**Additional context**

#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 1023, status = 104, data = 01010100000101010000000000000000
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.getMf1EmulatorConfig (package:chameleonultragui/bridge/chameleon.dart:819)
🐛 Sending: 11ef0fa9000000004800
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 1023, status = 104, data = 01010100000101010000000000000000
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.getMf1EmulatorConfig (package:chameleonultragui/bridge/chameleon.dart:819)
🐛 Sending: 11ef0fa9000000004800
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4009, status = 104, data = 0100010100
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.getMf1DetectionCount (package:chameleonultragui/bridge/chameleon.dart:652)
🐛 Sending: 11ef0fa5000000004c00
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4009, status = 104, data = 0100010100
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.getMf1DetectionCount (package:chameleonultragui/bridge/chameleon.dart:652)
🐛 Sending: 11ef0fa5000000004c00
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4009, status = 104, data = 0100010100
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.getMf1DetectionCount (package:chameleonultragui/bridge/chameleon.dart:652)
🐛 Sending: 11ef0fa5000000004c00
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4005, status = 104, data = 00000012
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4005, status = 104, data = 00000012
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.isMf1DetectionMode (package:chameleonultragui/bridge/chameleon.dart:641)
🐛 Sending: 11ef0fa7000000004a00
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4007, status = 104, data = 01
#0   ChameleonCommunicator.sendCmd (package:chameleonultragui/bridge/chameleon.dart:381)
#1   ChameleonCommunicator.getMf1DetectionCount (package:chameleonultragui/bridge/chameleon.dart:652)
🐛 Sending: 11ef0fa5000000004c00
#0   ChameleonCommunicator.onSerialMessage (package:chameleonultragui/bridge/chameleon.dart:353)
#1   BLESerial.connectSpecificInternal.<anonymous closure>.<anonymous closure> (package:chameleonultragui/connector/serial_ble.dart:202)
🐛 Received message: command = 4005, status = 104, data = 00000012

### PR DESCRIPTION
**Pull request by Foxushka**
Closes #291

### CODE REVIEW

**Comment by GameTec-live** [comment]
why gitignore the untranslated messages

**Comment by Foxushka** [comment]
File is useless

**Comment by GameTec-live** [comment]
> File is useless

afaik building breaks if you dont have it / all values in it

**Comment by Foxushka** [comment]
Not required on github

**Comment by GameTec-live** [comment]
hm, ok, flutter build also creates it... ig it can be removed then

**Review by GameTec-live — APPROVED** [review]

**Pull request merged**
