### PR TITLE
iOS and other fixes

### PR DESCRIPTION
**Pull request by Foxushka**

### CODE REVIEW

**Comment by Foxushka** [comment]
Some commands depends on https://github.com/RfidResearchGroup/ChameleonUltra/pull/131 and https://github.com/RfidResearchGroup/ChameleonUltra/pull/132, but they aren't used anyway and this can be merged safely

**Comment by aruznieto** [comment]
The change of the links it is unnecesary, we doesnt track any user... To put 2 links put only one...

**Comment by Foxushka** [comment]
I can't verify that it doesn't track users

**Comment by aruznieto** [comment]
> I can't verify that it doesn't track users and won't redirect to some malware sometime 

... domain is mine with CF DNS why do you suppose that I want to redirect the users to a malware or track users?

**Comment by Foxushka** [comment]
To earn some money

**Comment by aruznieto** [comment]
> To earn some money 

lol, without comments... If I need earn money do you think that I would be doing this? XD

**Comment by Foxushka** [comment]
Yes

**Comment by aruznieto** [comment]
> Yes

XD

**Comment by Foxushka** [comment]
If someone will offer you 10kk$ I 100% sure you won't decline this offer ☺️

**Comment by aruznieto** [comment]
> If someone will offer you 10kk$ I 100% sure you won't decline this offer ☺️

HAHAHAHA, and why do you think that https://nightly.link can do the same? 😜

**Comment by Foxushka** [comment]
Won't be our fault

**Comment by aruznieto** [comment]
> Won't be our fault 

If we provide that links, it will be our fault. And you change my links for that... xd

**Comment by aruznieto** [comment]
> Won't be our fault

If you need to know about the domain, I can invite you to Cloudflare and you will see it. But don't touch the domains.

**Comment by Foxushka** [comment]
Why are you changing my PR without my permission? There is no need for any links

**Comment by aruznieto** [comment]
But man, dont use nightly.link either! 😂 the problem is the same. I supose that you dont want to use the domain but for another reason, but dont worry I will fix it.

**Comment by Foxushka** [comment]
No, there is no any practical benefit to hide links under any domain

**Comment by aruznieto** [comment]
> No, there is no any practical benefit to hide links under any domain

Easy to remember a short link. I'm sure that if the domain was `chameleon.run`, you wouldn't complain. And I remember you... you are hide the link with nightly.link......

**Comment by Foxushka** [comment]
No, even for chameleon.run

**Comment by aruznieto** [comment]
> No, even for chameleon.run

Yes 😂. Do what you want. It will change again later. But I think it's nonsense what you are saying.  Short links always is better and it shouldn't bother you.

But I see that the problem is not that you can't check where the domain goes, simply you don't want to use it. But I remind you that you are not alone in the project. In your solo projects you do what you want, in projects where there are more people you don't.

**Comment by Foxushka** [comment]
No, you won't change it later. And this isn't your only project too.

**Comment by aruznieto** [comment]
> No, you won't change it later. And this isn't your only project too. 

I asked before put the links to Gametec you no 😜.

**Comment by Foxushka** [comment]
Unfortunately for you, @GameTec-live also agreed with my solution and has no questions to me

**Comment by Foxushka** [comment]
And btw when we will reach 1.0.0, we will move to releases and remove nightly.link too

**Comment by GameTec-live** [comment]
this discussion is silly, the readme will be rewritten sooner than later anyways to reflect the new features and better integrate screenshots, etc.

The more important stuff is if the crowdin python scripts work correctly..

**Comment by aruznieto** [comment]
> And btw when we will reach 1.0.0, we will move to releases and remove nightly.link too

Ok, If you use releases dont need another links. But I am going to distribute chameleonultragui.dev

And you know why he is always agreed right? Do you think it is ethical you who talk so much about it with my domain. 😜

**Comment by Foxushka** [comment]
I don't care about any ethics. We have different privacy concepts in life 
@GameTec-live doesn't want to upload any logs from app to anywhere (with user knowledge), there should be no any other links that can track users in readme too

**Comment by aruznieto** [comment]
> this discussion is silly, the readme will be rewritten sooner than later anyways to reflect the new features and better integrate screenshots, etc.
> 
> The more important stuff is if the crowdin python scripts work correctly..

Since fox doesn't care about that, I've already changed it. #239

**Comment by Foxushka** [comment]
User should always have chose in what link he can use

**Comment by aruznieto** [comment]
> User should always have chose in what link he can use

Ask the users and put 1. But you are giving now one link

**Comment by Foxushka** [comment]
@GameTec-live changed PR. Review latest changes please

**Comment by GameTec-live** [comment]
> @GameTec-live changed PR. Review latest changes please 

im not home until todays evening... the CU pr still needs to be merged too, so no stress :p

**Comment by Foxushka** [comment]
No, I'm about @aruznieto, he didn't checked latest changes where you added quick links

**Comment by aruznieto** [comment]
> No, I'm about @aruznieto, he didn't checked latest changes where you added quick links

I see it... yesterday. It is unnecessary to put two links for the same. You introduce more text and people read less. Show me any professional webpage the show you 2 links for the same download link.

**Comment by GameTec-live** [comment]
as said, its gonna be rewritten sooner than later, its pointless... Also; yes, there are websites with 2 links to the same thing. The flutter website has 2 different download buttons which redirect to the same file :p

**Comment by Foxushka** [comment]
@aruznieto btw I've suggested some fixes to Russian translation, check and approve them (to old phrases)

**Comment by aruznieto** [comment]
> @aruznieto btw I've suggested some fixes to Russian translation, check and approve them (to old phrases)

Ok. When I can.

Please remove old project.

**Comment by aruznieto** [comment]
About the links. Put it with []() of the nightly.link. It is so large

**Comment by aruznieto** [comment]
> @aruznieto btw I've suggested some fixes to Russian translation, check and approve them (to old phrases)

There are not changes on Crowdin...

**Comment by Foxushka** [comment]
I've added to previous translation, not new ones

**Comment by aruznieto** [comment]
> I've added to previous translation, not new ones

Not apeear on proofread

**Comment by aruznieto** [comment]
Don't touch docs links or put it with `[]()` (not visible).

**Comment by Foxushka** [comment]
> > I've added to previous translation, not new ones
> 
> Not apeear on proofread

Idk, I definitely send it, check all words



> Don't touch docs links or put it with `[]()` (not visible).

You can change it and send PR to my branch (don't push any changes here)

**Comment by Foxushka** [comment]
Screenshot_20230908-124026
Example

**Comment by aruznieto** [comment]
> Screenshot_20230908-124026
> Example

Now you have proofread permissions to accept your strings

**Review by GameTec-live — APPROVED** [review]

**Pull request merged**
