### PR TITLE
Qr sync

### PR DESCRIPTION
**Pull request by GameTec-live**
Adds export and import of all settings via QRCode

### CODE REVIEW

**Review by Akisame-AI — APPROVED** [review]
Tested and works. The default split size is rather large but as discussed in a future update we should include a test QR code to determine the ideal size for the device while suggesting a size based on the screen pixels size. Maybe 2 pixels per block in the QR code or a multiple thereof.

**Comment by GameTec-live** [comment]
Windows GH actions being funny, building locally works fine...

**Review by Foxushka — COMMENTED** [review]
Some changes I want from you to be done before merging:
1. Add option to exclude dictionary (or even select what data to move, but this goes for other PR) from export. They might be very huge and transferring them via QR is impossible 
2. Move export/import buttons in settings to be before about button. Doesn't look right
3. On 16:9 and default window size QR doesn't fit on one screen. Maybe scale it down, so it will fit window. Or make controls below QR. And convert controls to dropdown or input (slider for 3 values is ehhh)

**Comment by GameTec-live** [comment]
1) Plan for next pr, i want to do it properly ish (only exporting one card too for example) and i want the windows fixes merged for now... Also reduces pr size...

2) Will do

3) What? The QR Code scales to the maximum available size while still being readable, fumbled around with it a lot and it should fit on every size?
Slider for 3 values is maybe a bit wierd, but it fits in with the other slider, also nicer on mobile...

**Review by Akisame-AI — APPROVED** [review]
Made a small edit on the QR display code otherwise works nicely.
Well done!

**Pull request merged**
