### PR TITLE
Opencollective fun

### PR DESCRIPTION
**Pull request by GameTec-live**
Updated readme and added opencollective api resulting in supporters being shown in about screen

### CODE REVIEW

**Review by Foxushka — CHANGES_REQUESTED** [review]
Make FutureBuilder fetch names only when user open modal

**Comment by GameTec-live** [comment]
> Make FutureBuilder fetch names only when user open modal

how?

**Comment by Foxushka** [comment]
Idk, I definitely hate request each time someone goes to settings page

**Comment by GameTec-live** [comment]
> Idk, I definitely hate request each time someone goes to settings page

done ;)

**Review by Foxushka — APPROVED** [review]

**Pull request merged**
