### PR TITLE
Fix status bar color

### PR DESCRIPTION
**Pull request by Foxushka**
I'm sure there is better way, but I didn't found anything

### CODE REVIEW

**Comment by GameTec-live** [comment]
why would there be a need to "fix" the appbar, i dont see anything wrong... (and of theres a need to fix it, this is the "wrong way" lol)

**Comment by Foxushka** [comment]
Yes, it's fix for this
image

**Comment by GameTec-live** [comment]
ah, ok... there has to be a nicer way of fixing this, maybe @augustozanellato knows smthng

**Comment by nasaboy** [comment]
iOS and Android also have the same problem,see the video
https://github.com/GameTec-live/ChameleonUltraGUI/assets/5997682/ed81e285-4658-4bf2-884f-253c02f09b68

**Comment by GameTec-live** [comment]
does it exist on the textoverdlow issues branch? :thinking:

**Comment by GameTec-live** [comment]
ig now one just gotta search for a nice solution, because this aint it

**Review by GameTec-live — APPROVED** [review]

**Pull request merged**
